name: Build, Update, and Scan with Debug 

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-image .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image:latest
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        scan-type: 'image'

    - name: Clean up
      run: docker rmi my-image:latest

