name: Python Performance Benchmark

on:
  push:
    branches:
      - main

env:
  benchmark_list: deepcopy,float,python_startup

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Install system dependencies
        run: apk update && apk add bash python3 py3-pip gcc musl-dev python3-dev linux-headers

      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install pyperformance
        run: |
          source venv/bin/activate
          pip install --no-cache-dir pyperformance

      - name: Run pyperformance benchmarks
        run: |
          source venv/bin/activate
          pyperformance run --affinity=1 --benchmarks=${{ env.benchmark_list }}

