name: python-performance
on:
  push:
    branches:
      - main
env:
  benchmark_list: deepcopy, float

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install bash
        run: apk update && apk add bash

      - name: Install Python and dependencies
        run: apk add python3 py3-pip gcc musl-dev python3-dev linux-headers

      - name: Install pyperformance
        run: python3 -m pip install pyperformance

      - name: Run pyperformance
        run: python3 -m pyperformance run --affinity=1 --benchmark=${{ env.benchmark_list }}
